language: node_js
node_js:
- '8'
install:
- yarn install
script:
- yarn build
cache:
  yarn: true
deploy:
  provider: s3
  access_key_id:
    secure: HE4y/H40Toeyp1NsUe7juyiHZAWqlqxY7vxJsj9w4rCP4wq3rOy9CzsvY+ER1mgaIFwuIONap6rs5ysrXC0uLf/CXbTt15khrLAo70PX29bbDnwkSIm2Yt5r5D+0DkRkrK8PjtdefJJCY0hTtOxbkIvRYUyDLsWM8dMUFWl8WBepbNC/Qs5J4hXh3UXXYNqLO3rHsjczRicyaZwdyZGdaQVpmDMeJXQm8aZYeFESCZGw440Fn8UWbl4tdPhhWM6iRSz00px/mRUhcJ5FFQEnOUjgh1nLjoxbh+TQMj2ljeq8KUMo+mvceR90UQVxUZ7/NANg83yk+PUr6G7K0sfPAd2Bd6k53Pm0qF5TcWVtvsvxV3po3labv489Xl/K6r/YqvEbYcY0cCDNQhYMgjrtbdOcLAnxhHBaEVu2nDHswq/845/o2cXi1vUaZIiekJw1+nksyEsUpcX8BJJIZJeDu2QqcsFOF1zWIQ+1yc6OZ8Cp1zyy8QavxJykx2cCMvA/YEESsNfVLlRQpyqwmaO6ncAjyps97wrbgGMQRKtKC/1aQSvkTlc3Mdd6SFcNzyyMBN87/mifwB9xdX2pyS1LM97yiIQhdoyNbGcA0xxQSTI0RvHMGnAANFMhrr3XJtAFxoHhD5tFaAebBx330Qy/ehBqpVVTfl/Ton1cR4jo/bU=
  bucket: gmanu.me
  skip_cleanup: true
  local_dir: dist
  region: us-west-1
  secret_access_key:
    secure: IbEAxd7Vyd74YRHJCst8fc2gC/OVib67wpq6UkPJ07GFuIpsb9Wz22gM+NaTY8zW6rQzpT82JmLTNR1lIw6HuY59l7Kh8jsFj/JjdoOirOQbnzZtRhfKzOVezNFmsRY0uOlF/O8vAIrmZC5yY2FTthw1HOx3YqyZbm2KT383KJzCjMBi2ZbGsUK0HxyBuupRu8ZT9U+EAeF1ichgLSSURX9SxKGL52sNEgHonz8vHJNMeox3CoFMIKJfh1Eg675FoB5ngoI3YkyOzI4CKzFBW/obII4URN1xrziPwoO8MUZtL8yYVeBRYlv9UT8nQphHCbQV0aMhx2EGSnIMJp1gsr8AFHK4ik4Gf9a74emNrfya4RgYRihDQrZZ30ohpE2JcI2SPBinrgbF9qurlYtP1pWXEyPL45ILkobb9lgT1qs/nY/nByO3P6AzOKOZRZiCM9e+8PzHIH44FYyRdQ/oJw2HPgFRxjRk/yti7NTzjjZbwUYaXFZfzTrSTbmB9rxs/SVN7hmVBlfB1VR57rN2WK7QiZrBzs+OZ3/eyGQ6lDo3tEMUHTGBYySDVrJ2yBPJ2y2buhcXadnDb+3IhzpjUF+7E85enNsIWHlD0mAL2/WsArRZsoDPiCygUY7nmgwEOjlpTYnSXs0V/V38pWGmd1B9tJhiyHETjtt0MWn/nh0=
